apiVersion: v1
kind: ConfigMap
metadata:
  name: fnol-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: fnol-service, riskshield.io/domain: claims }
data:
  LOG_LEVEL: info
  PORT: "50081"
