cloud: {provider: aws, storageClass: gp3, ingressClass: alb}
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/riskshield-policy-admin
podAnnotations: {iam.amazonaws.com/role: riskshield-policy-admin}
envFrom:
  - secretRef: {name: policy-admin-aws-secrets}
