apiVersion: v1
kind: ConfigMap
metadata:
  name: self-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: self-service, riskshield.io/domain: customer }
data:
  LOG_LEVEL: info
  PORT: "50182"
