apiVersion: v1
kind: Service
metadata:
  name: self-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: self-service, riskshield.io/domain: customer }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50182, targetPort: 50182 }]
  selector: { app.kubernetes.io/name: self-service }
