cloud: {provider: aws, storageClass: gp3, ingressClass: alb}
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/riskshield-fraud-detection
podAnnotations: {iam.amazonaws.com/role: riskshield-fraud-detection}
envFrom:
  - secretRef: {name: fraud-detection-aws-secrets}
