apiVersion: v1
kind: ConfigMap
metadata:
  name: actuarial-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: actuarial-service, riskshield.io/domain: actuarial }
data:
  LOG_LEVEL: info
  PORT: "50120"
