apiVersion: v1
kind: Service
metadata:
  name: actuarial-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: actuarial-service, riskshield.io/domain: actuarial }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50120, targetPort: 50120 }]
  selector: { app.kubernetes.io/name: actuarial-service }
