apiVersion: v1
kind: ConfigMap
metadata:
  name: quote-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: quote-service, riskshield.io/domain: customer }
data:
  LOG_LEVEL: info
  PORT: "50181"
