apiVersion: v1
kind: Service
metadata:
  name: quote-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: quote-service, riskshield.io/domain: customer }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50181, targetPort: 50181 }]
  selector: { app.kubernetes.io/name: quote-service }
