apiVersion: v1
kind: Service
metadata:
  name: pricing-engine
  namespace: riskshield
  labels: { app.kubernetes.io/name: pricing-engine, riskshield.io/domain: actuarial }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50121, targetPort: 50121 }]
  selector: { app.kubernetes.io/name: pricing-engine }
