apiVersion: v1
kind: Service
metadata:
  name: accounting-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: accounting-service, riskshield.io/domain: finance }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50222, targetPort: 50222 }]
  selector: { app.kubernetes.io/name: accounting-service }
