apiVersion: v1
kind: ConfigMap
metadata:
  name: endorsement-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: endorsement-service, riskshield.io/domain: policy }
data:
  LOG_LEVEL: info
  PORT: "50041"
