apiVersion: v1
kind: Service
metadata:
  name: endorsement-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: endorsement-service, riskshield.io/domain: policy }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50041, targetPort: 50041 }]
  selector: { app.kubernetes.io/name: endorsement-service }
