apiVersion: v1
kind: ConfigMap
metadata:
  name: bordereau-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: bordereau-service, riskshield.io/domain: reinsurance }
data:
  LOG_LEVEL: info
  PORT: "50103"
