apiVersion: v1
kind: Service
metadata:
  name: scoring-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: scoring-service, riskshield.io/domain: fraud }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50143, targetPort: 50143 }]
  selector: { app.kubernetes.io/name: scoring-service }
