apiVersion: v1
kind: ConfigMap
metadata: { name: policy-admin, namespace: riskshield, labels: { app.kubernetes.io/name: policy-admin, riskshield.io/domain: policy } }
data:
  LOG_LEVEL: info
  SPRING_PROFILES_ACTIVE: prod
  ACORD_VERSION: "2024.1"
  SANCTION_SCREENING_URL: http://sanction-screening.riskshield-compliance:8080
