config:
  rootDomain: pomerium.riskshield.internal
  generateSignedJWT: true
authenticate:
  idp:
    provider: oidc
    url: https://keycloak.riskshield.internal
ingressController: { enabled: true }
