apiVersion: v1
kind: ConfigMap
metadata:
  name: treaty-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: treaty-service, riskshield.io/domain: reinsurance }
data:
  LOG_LEVEL: info
  PORT: "50100"
