apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: reporting-service, riskshield.io/domain: finance }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50223, targetPort: 50223 }]
  selector: { app.kubernetes.io/name: reporting-service }
