apiVersion: v1
kind: ConfigMap
metadata:
  name: nps-service
  namespace: riskshield
  labels: { app.kubernetes.io/name: nps-service, riskshield.io/domain: customer }
data:
  LOG_LEVEL: info
  PORT: "50184"
