apiVersion: v1
kind: Service
metadata:
  name: rating-engine
  namespace: riskshield
  labels: { app.kubernetes.io/name: rating-engine, riskshield.io/domain: underwriting }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50062, targetPort: 50062 }]
  selector: { app.kubernetes.io/name: rating-engine }
